version: "3.1"

services:

  db:
    image: postgres:10.5 
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tutorial
    ports:
      - "5432:5432"
    volumes:
      - docker-tutorial-postgres-data:/var/lib/postgresql/data

  dockertutorial:
    build: ../../src
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment: 
      Database__ConnectionString: host=db;port=5432;database=tutorial;password=password;username=postgres
    depends_on: 
      - db

volumes:
  docker-tutorial-postgres-data:
